package com.espressif.iot.db.greenrobot.daos;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.espressif.iot.db.greenrobot.daos.UserDB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * DAO for table USER_DB.
 */
public class UserDBDao extends AbstractDao<UserDB, Long>
{
    
    public static final String TABLENAME = "USER_DB";
    
    /**
     * Properties of entity UserDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties
    {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        
        public final static Property Email = new Property(1, String.class, "email", false, "EMAIL");
        
        public final static Property Password = new Property(2, String.class, "password", false, "PASSWORD");
        
        public final static Property Key = new Property(3, String.class, "key", false, "KEY");
        
        public final static Property IsLastLogin =
            new Property(4, boolean.class, "isLastLogin", false, "IS_LAST_LOGIN");
        
        public final static Property IsPwdSaved = new Property(5, boolean.class, "isPwdSaved", false, "IS_PWD_SAVED");
        
        public final static Property IsAutoLogin =
            new Property(6, boolean.class, "isAutoLogin", false, "IS_AUTO_LOGIN");
    };
    
    private DaoSession daoSession;
    
    public UserDBDao(DaoConfig config)
    {
        super(config);
    }
    
    public UserDBDao(DaoConfig config, DaoSession daoSession)
    {
        super(config, daoSession);
        this.daoSession = daoSession;
    }
    
    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists)
    {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "'USER_DB' (" + //
            "'_id' INTEGER PRIMARY KEY NOT NULL ," + // 0: id
            "'EMAIL' TEXT NOT NULL ," + // 1: email
            "'PASSWORD' TEXT NOT NULL ," + // 2: password
            "'KEY' TEXT NOT NULL ," + // 3: key
            "'IS_LAST_LOGIN' INTEGER NOT NULL ," + // 4: isLastLogin
            "'IS_PWD_SAVED' INTEGER NOT NULL ," + // 5: isPwdSaved
            "'IS_AUTO_LOGIN' INTEGER NOT NULL );"); // 6: isAutoLogin
    }
    
    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists)
    {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'USER_DB'";
        db.execSQL(sql);
    }
    
    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UserDB entity)
    {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getEmail());
        stmt.bindString(3, entity.getPassword());
        stmt.bindString(4, entity.getKey());
        stmt.bindLong(5, entity.getIsLastLogin() ? 1l : 0l);
        stmt.bindLong(6, entity.getIsPwdSaved() ? 1l : 0l);
        stmt.bindLong(7, entity.getIsAutoLogin() ? 1l : 0l);
    }
    
    @Override
    protected void attachEntity(UserDB entity)
    {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }
    
    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset)
    {
        return cursor.getLong(offset + 0);
    }
    
    /** @inheritdoc */
    @Override
    public UserDB readEntity(Cursor cursor, int offset)
    {
        UserDB entity = new UserDB( //
            cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // email
            cursor.getString(offset + 2), // password
            cursor.getString(offset + 3), // key
            cursor.getShort(offset + 4) != 0, // isLastLogin
            cursor.getShort(offset + 5) != 0, // isPwdSaved
            cursor.getShort(offset + 6) != 0 // isAutoLogin
            );
        return entity;
    }
    
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UserDB entity, int offset)
    {
        entity.setId(cursor.getLong(offset + 0));
        entity.setEmail(cursor.getString(offset + 1));
        entity.setPassword(cursor.getString(offset + 2));
        entity.setKey(cursor.getString(offset + 3));
        entity.setIsLastLogin(cursor.getShort(offset + 4) != 0);
        entity.setIsPwdSaved(cursor.getShort(offset + 5) != 0);
        entity.setIsAutoLogin(cursor.getShort(offset + 6) != 0);
    }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(UserDB entity, long rowId)
    {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(UserDB entity)
    {
        if (entity != null)
        {
            return entity.getId();
        }
        else
        {
            return null;
        }
    }
    
    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable()
    {
        return true;
    }
    
}
