package com.espressif.iot.type.help;

public enum HelpType
{
    CONFIGURE,
    MESH_CONFIGURE,
    USAGE_PLUG,
    USAGE_PLUGS,
    USAGE_LIGHT,
    USAGE_REMOTE,
    USAGE_HUMITURE,
    USAGE_FLAMMABLE,
    USAGE_VOLTAGE,
    UPGRADE_LOCAL,
    UPGRADE_ONLINE,
    SSS_USAGE_DEVICE,
    SSS_UPGRADE,
    SSS_MESH_CONFIGURE
}
